In [7]:
import numpy as np

In [8]:
list1=[1,2,3,4,5]

In [9]:
x=np.array(list1)

In [10]:
type(x)

numpy.ndarray

In [11]:
np.shape(x)

(5,)

In [12]:
np.array([2,2,2,2])

array([2, 2, 2, 2])

In [13]:
np.array([3,3,3,3])

array([3, 3, 3, 3])

In [14]:
arr2d=np.array([[1,1,1],[2,2,2],[3,3,3]])

In [15]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [16]:
arr2d.shape

(3, 3)

In [17]:
arr2d[4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [18]:
#array manuplation

In [20]:
import numpy as np

In [21]:
array_1=np.array([1,2,3,4,5,6,4,2,2,1])

In [23]:
array_2=np.array([[2,3,2,4,6],[5,6,3,2,4]])

In [24]:
array_1.shape

(10,)

In [25]:
array_2.shape

(2, 5)

In [26]:
np.reshape(array_1,(2,5))

array([[1, 2, 3, 4, 5],
       [6, 4, 2, 2, 1]])

In [27]:
array_1.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 4, 2, 2, 1]])

In [28]:
array_1.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [29]:
array_2

array([[2, 3, 2, 4, 6],
       [5, 6, 3, 2, 4]])

In [31]:
np.ndarray.flatten(array_2)

array([2, 3, 2, 4, 6, 5, 6, 3, 2, 4])

In [32]:
array_2.ravel()

array([2, 3, 2, 4, 6, 5, 6, 3, 2, 4])

In [33]:
array_2.shape

(2, 5)

In [34]:
#array creation function

In [35]:
import numpy as np

In [36]:
np.full((2,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [38]:
np.full((5,5),fill_value=0,dtype=np.longdouble)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float128)

In [40]:
np.full(dtype=np.longdouble,shape=(5,5),fill_value=0)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float128)

In [41]:
np.random.rand(2,5)

array([[0.98264766, 0.00882361, 0.50769883, 0.36471524, 0.04206525],
       [0.15412217, 0.81851441, 0.76846992, 0.4505926 , 0.7817365 ]])